import cartoons.PlayVideo;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class Home extends javax.swing.JFrame {
    /**
     * Creates new form mainWindow
     */
    public Home() {
        initComponents();


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        header = new javax.swing.JPanel();
        Slider = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(77, 77, 77));
        header.setPreferredSize(new java.awt.Dimension(2000, 50));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 690, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
                headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        JLabel title = new JLabel("Movie Streaming Application");
        title.setFont(new Font("Arial", Font.PLAIN, 20));
        title.setSize(500, 20);
        title.setLocation(500, 20);
        title.setForeground(Color.WHITE);
        header.add(title);

        //jButton4.setBorderPainted(false);
        //jButton4.setFocusPainted(false);
        JComboBox comboBox = new JComboBox(new Object[]{"","kiddo", "devara", "tom & Jerry"});
        AutoCompleteDecorator.decorate(comboBox);
        comboBox.setSize(150, 30);
        comboBox.setLocation(1200, 20);

        JTextField jtf = new JTextField(20);
        String[] tab = {"kiddo", "devara", "tom & Jerry"};
        JList list = new JList(tab); //data has type Object[]
        AutoCompleteDecorator.decorate(list, jtf, ObjectToStringConverter.DEFAULT_IMPLEMENTATION);
        jtf.setSize(150, 30);
        jtf.setLocation(1200, 20);

        JButton searchButton = new JButton();
        try {
            File video_source = new File("/home/silla/Downloads/search.png");
            Image img = ImageIO.read(video_source);
            searchButton.setIcon(new ImageIcon(img));
        } catch (Exception ex) {
            System.out.println(ex);
        }
        searchButton.setSize(50, 30);
        searchButton.setLocation(1340, 20);

        jButton4.setText("Login");
        jButton4.setSize(100, 30);
        jButton4.setLocation(1400, 20);
     //   jButton5.setBorderPainted(false);
       // jButton5.setFocusPainted(false);
        jButton5.setText("Register");
        jButton5.setSize(100, 30);
        jButton5.setLocation(1500, 20);

        header.add(jButton4);
        header.add(jButton5);
       // header.add(comboBox);
        header.add(jtf, BorderLayout.NORTH);
        header.add(searchButton);
        //pan.add(list, BorderLayout.CENTER);
        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        Slider.setBackground(new java.awt.Color(103, 103, 103));
        Slider.setAlignmentX(0.0F);
        Slider.setAlignmentY(0.0F);
        Slider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Slider.setMinimumSize(new java.awt.Dimension(150, 150));
        Slider.setPreferredSize(new java.awt.Dimension(100, 900));
        //Slider.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        //jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AKRAM\\Desktop\\Home-50.png")); // NOI18N
       // jButton1.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setText(" Cartoon ");
        jButton1.setSize(100, 100);

        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setText(" Movies ");
        jButton2.setSize(100, 100);

        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setText(" News ");
        jButton3.setSize(100, 100);

        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.setText(" Kids ");
        jButton6.setSize(100, 100);
        Slider.add(jButton1);
        Slider.add(jButton2);

        Slider.add(jButton3);
        Slider.add(jButton6);


        getContentPane().add(Slider, java.awt.BorderLayout.LINE_START);

        footer.setBackground(new java.awt.Color(77, 77, 77));
        footer.setMinimumSize(new java.awt.Dimension(50, 50));
        footer.setPreferredSize(new java.awt.Dimension(673, 50));

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
                footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 690, Short.MAX_VALUE)
        );
        footerLayout.setVerticalGroup(
                footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );
        JLabel footerLabel = new JLabel("Powered by Mahindra University, Hyderabad.");
        footerLabel.setFont(new Font("Arial", Font.PLAIN, 20));
        footerLabel.setSize(500, 20);
        footerLabel.setLocation(1000, 20);
        footerLabel.setForeground(Color.WHITE);
        footer.add(footerLabel);
        getContentPane().add(footer, java.awt.BorderLayout.PAGE_END);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setMinimumSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
                mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 540, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
                mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 391, Short.MAX_VALUE)
        );

        JLabel centerLabel = new JLabel("Welcome!");
        centerLabel.setFont(new Font("Arial", Font.PLAIN, 50));
        centerLabel.setSize(1000, 100);
        centerLabel.setLocation(500, 150);
        centerLabel.setForeground(Color.BLACK);
       // main.add(centerLabel);

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();

        searchButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("search button is clicked");
                PlayVideo player = new PlayVideo();
                player.play("VID_URL");
            }
        });
        jButton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                LoginPage log = new LoginPage();
            }});

        jButton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                MyFrame f = new MyFrame();
            }});

        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("cartoon clicked");
                BufferedImage image = null;
                try {
                    image = ImageIO.read(new File("/home/silla/Desktop/my-projects/scala/37.2/prioriri-queue/MSApp/src/cartoon.jpeg"));
                } catch (IOException ex) {
                    throw new RuntimeException(ex);
                }
                JLabel cartoonLabel = new JLabel(new ImageIcon(image));
                cartoonLabel.setSize(200, 200);
                cartoonLabel.setLocation(100, 30);
                cartoonLabel.setBorder(BorderFactory.createLineBorder(Color.black, 5));
                JButton btnNewButton = new JButton("Play");
                btnNewButton.setFont(new Font("Tahoma", Font.PLAIN, 15));
                btnNewButton.setBounds(100, 200, 200, 30);
                main.add(btnNewButton);
                main.add(cartoonLabel);
                main.revalidate(); // Revalidate the panel to reflect the changes
                main.repaint();
//Add a mouse listener to get the click event

                btnNewButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        System.out.println("Image is clicked");
                         PlayVideo player = new PlayVideo();
                player.play("VID_URL");
                    }
                });

            }});
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });


    }

    // Variables declaration - do not modify
    private javax.swing.JPanel Slider;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1; //cartoon category
    private javax.swing.JButton jButton2; //Moview Category
    private javax.swing.JButton jButton3; // kids
    private javax.swing.JButton jButton4; //news
    private javax.swing.JButton jButton5; //login
    private javax.swing.JButton jButton6; // register

    private javax.swing.JPanel main;
// End of variables declaration
private void getVideo(){
    File video_source = new File("/home/silla/Downloads/cartoon.mp4");
    Media m = new Media(video_source.toURI().toString());
    //Media m = new Media("https://www.youtube.com/embed/qzW6mgfY5X4");
    MediaPlayer player = new MediaPlayer(m);
    player.play();
    MediaControl mediaControl = new MediaControl(player);

    StackPane root = new StackPane();
    Scene scene = new Scene(root);
    scene.setRoot(mediaControl);

    // add video to stackpane
    JFXPanel videoPanel = new JFXPanel();
    videoPanel.setBorder(new LineBorder(new Color(0, 0, 0), 2));
    videoPanel.setBounds(155, 60, 509, 317);
    videoPanel.setScene(scene);
    main.add(videoPanel);

}
}